import 'package:flutter/material.dart';
import '../../domain/entities/ai_analysis.dart';

/// AI Analysis view widget - Display AI-generated root cause analysis
/// Read-only rendering of analysis data
///
/// Features:
/// - Root cause hypothesis
/// - Confidence score visualization
/// - Debug checklist
/// - Suggested actions
/// - Related error patterns
/// - Analysis metadata (model, tokens, cost, duration)
///
/// States:
/// - Analysis available: Show full analysis
/// - Analysis not available: Show empty state with helpful message
class AiAnalysisView extends StatelessWidget {
  final AiAnalysis? analysis;

  const AiAnalysisView({
    super.key,
    this.analysis,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    if (analysis == null) {
      return _buildNotAvailableState(theme);
    }

    return SingleChildScrollView(
      padding: const EdgeInsets.all(24.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header with AI icon
          Row(
            children: [
              Icon(
                Icons.psychology,
                size: 32,
                color: theme.colorScheme.primary,
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'AI Root Cause Analysis',
                      style: theme.textTheme.headlineSmall,
                    ),
                    Text(
                      'Generated by ${analysis!.modelUsed}',
                      style: theme.textTheme.bodySmall?.copyWith(
                        color: theme.colorScheme.onSurface.withOpacity(0.7),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),

          const SizedBox(height: 24),

          // Confidence score
          _buildConfidenceScore(theme),

          const SizedBox(height: 24),

          // Root cause hypothesis
          _buildSection(
            theme,
            'Root Cause Hypothesis',
            Icons.lightbulb_outline,
            analysis!.rootCauseHypothesis,
          ),

          const SizedBox(height: 24),

          // Debug checklist
          _buildListSection(
            theme,
            'Debug Checklist',
            Icons.checklist,
            analysis!.debugChecklist,
          ),

          const SizedBox(height: 24),

          // Suggested actions
          _buildListSection(
            theme,
            'Suggested Actions',
            Icons.task_alt,
            analysis!.suggestedActions,
          ),

          const SizedBox(height: 24),

          // Related error patterns
          if (analysis!.relatedErrorPatterns.isNotEmpty) ...[
            _buildListSection(
              theme,
              'Related Error Patterns',
              Icons.pattern,
              analysis!.relatedErrorPatterns,
            ),
            const SizedBox(height: 24),
          ],

          // Metadata
          _buildMetadataSection(theme),
        ],
      ),
    );
  }

  Widget _buildNotAvailableState(ThemeData theme) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(48.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              Icons.psychology_outlined,
              size: 80,
              color: theme.colorScheme.onSurface.withOpacity(0.3),
            ),
            const SizedBox(height: 24),
            Text(
              'No AI Analysis Available',
              style: theme.textTheme.titleLarge?.copyWith(
                color: theme.colorScheme.onSurface.withOpacity(0.7),
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 12),
            Text(
              'AI analysis has not been generated for this incident yet.\n'
              'Request an analysis from the incident detail view.',
              style: theme.textTheme.bodyMedium?.copyWith(
                color: theme.colorScheme.onSurface.withOpacity(0.6),
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 24),
            OutlinedButton.icon(
              onPressed: null, // Disabled in this view
              icon: const Icon(Icons.psychology),
              label: const Text('Analysis Not Available'),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildConfidenceScore(ThemeData theme) {
    final confidencePercent = analysis!.confidenceScore * 100;
    final color = confidencePercent >= 80
        ? Colors.green
        : confidencePercent >= 60
            ? Colors.orange
            : Colors.red;

    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: color.withOpacity(0.5)),
      ),
      child: Row(
        children: [
          Container(
            width: 60,
            height: 60,
            decoration: BoxDecoration(
              color: color.withOpacity(0.2),
              shape: BoxShape.circle,
            ),
            child: Center(
              child: Text(
                '${confidencePercent.toStringAsFixed(0)}%',
                style: theme.textTheme.titleLarge?.copyWith(
                  color: color,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Confidence Score',
                  style: theme.textTheme.titleMedium?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  _getConfidenceLabel(confidencePercent),
                  style: theme.textTheme.bodySmall?.copyWith(
                    color: theme.colorScheme.onSurface.withOpacity(0.7),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  String _getConfidenceLabel(double percent) {
    if (percent >= 80) {
      return 'High confidence in the analysis';
    } else if (percent >= 60) {
      return 'Moderate confidence - manual verification recommended';
    } else {
      return 'Low confidence - requires further investigation';
    }
  }

  Widget _buildSection(
    ThemeData theme,
    String title,
    IconData icon,
    String content,
  ) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: theme.colorScheme.surfaceVariant,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(icon, color: theme.colorScheme.primary),
              const SizedBox(width: 8),
              Text(
                title,
                style: theme.textTheme.titleMedium?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          Text(
            content,
            style: theme.textTheme.bodyMedium,
          ),
        ],
      ),
    );
  }

  Widget _buildListSection(
    ThemeData theme,
    String title,
    IconData icon,
    List<String> items,
  ) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: theme.colorScheme.surfaceVariant,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(icon, color: theme.colorScheme.primary),
              const SizedBox(width: 8),
              Text(
                title,
                style: theme.textTheme.titleMedium?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          ...items.asMap().entries.map((entry) {
            final index = entry.key;
            final item = entry.value;
            return Padding(
              padding: EdgeInsets.only(
                bottom: index < items.length - 1 ? 8 : 0,
              ),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Container(
                    width: 24,
                    height: 24,
                    decoration: BoxDecoration(
                      color: theme.colorScheme.primaryContainer,
                      shape: BoxShape.circle,
                    ),
                    child: Center(
                      child: Text(
                        '${index + 1}',
                        style: theme.textTheme.labelSmall?.copyWith(
                          color: theme.colorScheme.onPrimaryContainer,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Padding(
                      padding: const EdgeInsets.only(top: 2),
                      child: Text(
                        item,
                        style: theme.textTheme.bodyMedium,
                      ),
                    ),
                  ),
                ],
              ),
            );
          }).toList(),
        ],
      ),
    );
  }

  Widget _buildMetadataSection(ThemeData theme) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: theme.colorScheme.secondaryContainer.withOpacity(0.5),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Analysis Metadata',
            style: theme.textTheme.titleSmall?.copyWith(
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 12),
          _buildMetadataItem(theme, 'Model', analysis!.modelUsed),
          _buildMetadataItem(
            theme,
            'Tokens',
            '${analysis!.totalTokens} (prompt: ${analysis!.promptTokens}, completion: ${analysis!.completionTokens})',
          ),
          _buildMetadataItem(theme, 'Cost', analysis!.formattedCost),
          _buildMetadataItem(
            theme,
            'Duration',
            '${analysis!.analysisDurationMs}ms',
          ),
          _buildMetadataItem(
            theme,
            'Analyzed At',
            _formatDateTime(analysis!.analyzedAt),
          ),
        ],
      ),
    );
  }

  Widget _buildMetadataItem(ThemeData theme, String label, String value) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            width: 100,
            child: Text(
              '$label:',
              style: theme.textTheme.bodySmall?.copyWith(
                color: theme.colorScheme.onSecondaryContainer.withOpacity(0.7),
              ),
            ),
          ),
          Expanded(
            child: Text(
              value,
              style: theme.textTheme.bodySmall?.copyWith(
                color: theme.colorScheme.onSecondaryContainer,
                fontWeight: FontWeight.w500,
              ),
            ),
          ),
        ],
      ),
    );
  }

  String _formatDateTime(DateTime dateTime) {
    return '${dateTime.year}-${dateTime.month.toString().padLeft(2, '0')}-${dateTime.day.toString().padLeft(2, '0')} '
        '${dateTime.hour.toString().padLeft(2, '0')}:${dateTime.minute.toString().padLeft(2, '0')}';
  }
}
